# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest  

    steps:
    - uses: actions/checkout@v4
    - name: Steup do NodeJS
      uses: actions/setup-node@v4.0.2
      with: 
        node-version: 22.2.0

    - name: Instalação do Mocha e dos pacotes para teste
      run: |
        cd src;
        npm install -g mocha;
        npm install

    - name: Execução do teste
      run: mocha src/test/convert.js
      
    - name: Construção da imagem Docker 
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@94f8f8c2eec4bc3f1d78c1755580779804cb87b2
      uses: docker/build-push-action@v6.0.1
      with:
        context: src
        file: DockerFile
        push: true
        tahs: |
          eltergirotto/aula-conversao-temperatura:v1
          eltergirotto/aula-conversao-temperatura:latest
    
